const zh = {
 title: "分享、双人指南与来源统计",
 body: "相处说明书免费生成，仅公开你确认的三句话，以及你主动开启的参考类型或四维定性标签。持有链接的人都能查看这些内容；原始答案、分数、订单号和完整报告不会随卡片公开。双人指南要求双方分别解锁各自的完整报告，已解锁的报告无需重复购买；发起者也可以“请 TA”，在对方同意加入时为其打开报告，邀请页只会显示已备好，不显示付款人或金额。发起者须另行同意公开所选关系、四维类别、问卷版本和测试日期；参与者先查看自己的正常结果，再独立确认加入。付费或恢复记录都不代表同意加入双人指南，发起者看不到对方的付款行为。生成的指南仅双方签名浏览器可读。你可在“我的分享”关闭单人卡，在“我的双人指南”关闭邀请或撤回指南；独立邀请不受单人卡关闭影响，创建时明确关联卡片的邀请会随卡片关闭。已下载的图片和他人保存的内容无法收回。旧版已生成的指南仍可查看或撤回，旧邀请不再接受新参与。",
 measurement: "我们用签名浏览器标识记录单人卡或邀请的首次有效触达，并在7日内关联该浏览器的首次测试完成；两种来源互斥，这不代表真实人数或因果增量。我们还在自有数据库记录本人结果的权益曝光、点击入口、打开支付、选定结果和继续邀请等最小事件，将已核实归属的结果编号与服务器判断的权益状态关联，用于分析功能使用及同一结果的购买转化。这些事件不含答案、分数或偏好类别，不发送给Google。复制链接和请求保存图片不表示实际分享成功。事件保留90日，来源归因明细保留180日；用于支付返回的续接记录在到期或完成30日后可清理，报告、订单、邀请与指南作为业务记录保留。统计失败不影响测试或支付。分享、邀请、双方指南及分享管理页面不向Google发送采集请求，完整链接及私人内容不会作为统计参数发送。",
};
const en: typeof zh = {
 title: "Sharing, guides for two and referral measurement",
 body: "A personal guide is free to create. It publishes only the three statements you confirm and any reference type or qualitative dimensions you enable. Anyone with the link can read them; answers, scores, order numbers and full reports are not published with the card. For a guide for two, both people must unlock the report they use. A report already unlocked needs no additional purchase. The host can also cover the other person’s report, which opens when they agree to join; the invitation only says it is covered, never who paid or how much. The host separately agrees to publish the relationship they choose, four qualitative categories, the questionnaire version and test date. The other person sees their normal result first, then separately agrees to join. Payment and restoring records do not count as consent; the host cannot see the other person’s payment activity. Generated guides are readable only by the two signed browsers. Close a card in My shares, or close an invitation or withdraw a guide in My guides for two. Independent invitations are unaffected by closing a card; invitations explicitly linked to a card close with it. Downloaded images and copies held by others cannot be recalled. Existing guides from the previous version remain readable and can be withdrawn; old invitations no longer accept new participants.",
 measurement: "We use signed browser identifiers to associate the first valid card or invitation visit with the browser’s first test completion within seven days. The two sources are mutually exclusive; these are browsers, not people or causal impact. Our own database also records minimal events for viewing a result’s benefit, selecting an entry, opening payment, selecting a result and resuming a comparison. We associate an ownership-verified result ID with server-checked access status to understand use and purchases of that same result. These events contain no answers, scores or preference categories and are not sent to Google. Copying a link and requesting an image save do not prove a share was sent. Events are kept for 90 days and referral details for 180 days. Payment-return continuation records may be removed 30 days after expiry or completion; reports, orders, invitations and guides remain business records. Measurement failures do not block tests or payments. Sharing, invitation, comparison and sharing-management pages send no Google collection requests; full capability links and private content are not sent as analytics parameters.",
};
export const shareHelpMessages = { zh, en };
