import type { Locale } from "@/lib/i18n/locale";

const zh = {
  title: "我的相处说明书", subtitle: "和我相处，可以从这三件事开始。", create: "生成我的相处说明书", publish: "确认公开并生成", save: "保存图片", copy: "复制链接", copied: "链接已复制", closeShare: "关闭分享", disclaimer: "本次探索，不定义我。", testNote: "用日常情境题，看见你的四维人格偏好。",
  entryTitle: "把你认同的相处方式，整理成一张卡。", entryDescription: "选三条像你的描述，预览后再决定是否公开。", selected: "已选", chooseThree: "请选择三条像你的描述", maximumSelected: "请先取消一条，再选择另一条。", showType: "显示参考类型", showDimensions: "显示四维倾向", publicWarning: "这些句子也可能体现你的偏好。任何持有链接的人都能查看你选择公开的内容。", preview: "预览", previewPlaceholder: "生成后显示访问入口", publishing: "正在生成…", loading: "正在读取…", created: "相处说明书已生成", close: "关闭", retry: "重试", retryImage: "重新生成图片", imageFailed: "图片暂时无法加载，仍可复制链接。", longPress: "长按图片保存", manualCopy: "请选中下面的链接，手动复制。", adjust: "调整内容", newShareNotice: "将生成新的分享；旧分享仍可在我的分享中关闭。", timeout: "生成时间较长，可重试或稍后在我的分享查看。", error: "暂时无法完成，请重试。", sessionUnavailable: "当前会话不可用，请允许 Cookie 后重新打开页面。", unavailable: "这份分享已关闭或不存在。", myShares: "我的分享", myReports: "我的报告", empty: "你还没有生成相处说明书。", publicScope: "公开范围", linesOnly: "三条相处提示", referenceType: "参考类型", qualitativeDimensions: "四维定性倾向", partialBalanced: "部分维度接近均衡，参考类型不代表四个维度都有明确偏向。", allBalanced: "四个维度都接近均衡，参考类型仅作对照。", closeConfirmation: "关闭后，链接将不再展示内容。已被保存或转发的图片无法收回。", cancel: "取消", revoked: "已关闭", active: "公开中", closing: "正在关闭…", loadMore: "查看更多", publicHeading: "一份相处说明书", publicDescription: "这三条描述由分享者从本次测试的候选中选定，也可以成为一次沟通的开始。", freeNote: "32题轻量版约5分钟", pairTitle: "也可以看看你们之间", pairBody: "各自完成测试并确认后，可以生成一份只给你们两个人的双人指南。", pairLink: "了解双人指南", help: "了解测试与分享", scan: "扫码查看，生成你的相处说明书", scanShort: "扫码查看", createdAt: "创建时间", imageAlt: "相处说明书图片", start: "开始我的测试", noJs: "请启用 JavaScript 以生成和管理分享。公开说明书仍可直接阅读。", tooMany: "操作较频繁，请稍后重试。", requestConflict: "这次请求的内容已改变，请调整内容后重新生成。",
};
const en: typeof zh = {
  title: "A little guide to understanding me", subtitle: "Three things that may help us understand each other.", create: "Create my guide", publish: "Publish and create", save: "Save image", copy: "Copy link", copied: "Link copied", closeShare: "Close this share", disclaimer: "A snapshot for reflection, not a definition of me.", testNote: "Explore your four preferences through everyday situations.",
  entryTitle: "Put the ways you relate to others into a card.", entryDescription: "Choose three descriptions that feel like you, then preview before publishing.", selected: "Selected", chooseThree: "Choose three descriptions that feel like you", maximumSelected: "Deselect one before choosing another.", showType: "Show reference type", showDimensions: "Show four preferences", publicWarning: "These sentences may also suggest your preferences. Anyone with the link can view the content you choose to publish.", preview: "Preview", previewPlaceholder: "A viewing link appears after publishing", publishing: "Creating…", loading: "Loading…", created: "Your guide is ready", close: "Close", retry: "Try again", retryImage: "Reload image", imageFailed: "The image could not load. You can still copy the link.", longPress: "Touch and hold the image to save it", manualCopy: "Select the link below and copy it manually.", adjust: "Adjust content", newShareNotice: "This will create a new share. You can close the old one in My shares.", timeout: "This is taking longer than usual. Retry or check My shares later.", error: "This could not be completed. Please try again.", sessionUnavailable: "Your session is unavailable. Allow cookies and reopen the page.", unavailable: "This share is closed or does not exist.", myShares: "My shares", myReports: "My reports", empty: "You have not created a guide yet.", publicScope: "Public content", linesOnly: "Three tips for relating to me", referenceType: "Reference type", qualitativeDimensions: "Four qualitative preferences", partialBalanced: "Some dimensions are close to balanced, so the reference type does not mean all four have a clear lean.", allBalanced: "All four dimensions are close to balanced, so the reference type is only a point of comparison.", closeConfirmation: "Closing removes the content from this link. Images already saved or forwarded cannot be recalled.", cancel: "Cancel", revoked: "Closed", active: "Public", closing: "Closing…", loadMore: "Show more", publicHeading: "A guide to understanding someone", publicDescription: "The person sharing this guide chose these three descriptions from their test suggestions. They can also be a starting point for a conversation.", freeNote: "About 5 minutes for 32 items", pairTitle: "You can also look at the two of you", pairBody: "After you each complete a test and agree, you can create a guide only the two of you can read.", pairLink: "Explore guides for two", help: "About the test and sharing", scan: "Scan to read and create your own guide", scanShort: "Scan to read", createdAt: "Created", imageAlt: "Image of a personal guide", start: "Start my test", noJs: "Enable JavaScript to create and manage shares. Published guides remain readable without it.", tooMany: "Too many requests. Please try again shortly.", requestConflict: "The content of this request has changed. Adjust the content to create a new share.",
};
export const shareMessages: Record<Locale, typeof zh> = { zh, en };
