import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { expect, test, type APIRequestContext } from "@playwright/test";
import { getQuestionnaire } from "../../src/lib/questionnaires";

const origin = process.env.E2E_BASE_URL ?? "http://localhost:3000";
const evidence = "docs/verification/share-growth";
async function seed(request: APIRequestContext, en = false) {
  await request.get(en ? "/" : "/zh");
  const q = getQuestionnaire(en ? "en32-v1" : "legacy32-v1")!;
  const response = await request.post("/api/results", { data: { questionnaireId: q.id, answers: q.questions.map(question => ({ questionId: question.id, value: question.reverse ? -2 : 2 })) } });
  expect(response.status()).toBe(201);
  const result = (await response.json()).data;
  const options = await request.get(`/api/results/${result.id}/share-options`);
  expect(options.status()).toBe(200);
  return { result, options: (await options.json()).data };
}
async function publish(request: APIRequestContext, en = false) {
  const seeded = await seed(request, en);
  const body = { resultId: seeded.result.id, selectedIds: seeded.options.defaultSelectedIds, showType: false, showDimensions: false, requestId: randomUUID(), consentVersion: "share-public-v1" };
  const response = await request.post("/api/shares", { data: body, headers: { origin } });
  expect(response.status()).toBe(201);
  return { ...seeded, body, share: (await response.json()).data };
}

for (const en of [false, true]) test(`share public capability privacy, ownership, retry, PNG and revoke ${en ? "en" : "zh"}`, async ({ page, browser }, info) => {
  test.setTimeout(120_000);
  const { result, share, body } = await publish(page.request, en);
  const stranger = await browser.newContext({ baseURL: origin });
  await stranger.request.get("/");
  expect((await stranger.request.get(`/api/results/${result.id}/share-options`)).status()).toBe(404);
  expect((await stranger.request.delete(`/api/shares/${share.id}`, { headers: { origin } })).status()).toBe(404);
  const retry = await page.request.post("/api/shares", { data: body, headers: { origin } });
  expect(retry.status()).toBe(200);
  expect((await retry.json()).data.id).toBe(share.id);
  expect((await page.request.post("/api/shares", { data: { ...body, showType: true }, headers: { origin } })).status()).toBe(409);
  expect(Object.keys(share.snapshot).sort()).toEqual(["disclaimer", "lines", "locale", "version"]);
  expect(share.token).toMatch(/^[A-Za-z0-9_-]{32}$/);
  const path = new URL(share.url).pathname;
  const raw = await stranger.request.get(path);
  const html = await raw.text();
  expect(html).not.toContain(result.id);
  expect(html).not.toContain(share.id);
  expect(html).not.toContain("share-v1:EI");
  expect(html).not.toContain('"dimensions":');
  expect(html).not.toContain('"typeLabel":');
  expect(html).not.toContain(result.type);
  expect(raw.headers()["referrer-policy"]).toBe("no-referrer");
  expect(raw.headers()["cache-control"]).toContain("no-store");
  const viewer = await stranger.newPage();
  await viewer.goto(path);
  await expect(viewer.locator("[data-share-card] ol li")).toHaveCount(3);
  for (const line of share.snapshot.lines) await expect(viewer.locator("[data-share-card]")).toContainText(line);
  await mkdir(evidence, { recursive: true });
  await viewer.setViewportSize(info.project.name === "mobile" ? { width: 393, height: 852 } : { width: 1363, height: 936 });
  await expect(viewer.locator("[data-share-card]")).toBeVisible();
  await expect.poll(() => viewer.locator("[data-share-card]").evaluate(node => node.getAnimations({ subtree: true }).filter(a => a.playState === "running").length)).toBe(0);
  await viewer.screenshot({ path: `${evidence}/friend-${en ? "en" : "zh"}-${info.project.name}.png`, fullPage: true, animations: "disabled" });
  const png = await stranger.request.get(new URL(share.imageUrl).pathname);
  expect(png.status()).toBe(200);
  expect(png.headers()["content-type"]).toContain("image/png");
  const bytes = await png.body();
  expect(bytes.readUInt32BE(16)).toBe(960);
  expect(bytes.readUInt32BE(20)).toBe(1280);
  await writeFile(`${evidence}/guide-${en ? "en" : "zh"}.png`, bytes);
  await writeFile(`${evidence}/guide-${en ? "en" : "zh"}.expected-url.txt`, share.url);
  const og = await stranger.request.get(`${path}/opengraph-image`);
  expect(og.status()).toBe(200);
  const ogBytes = await og.body();
  expect(ogBytes.readUInt32BE(16)).toBe(1200);
  expect(ogBytes.readUInt32BE(20)).toBe(630);
  await writeFile(`${evidence}/og-${en ? "en" : "zh"}.png`, ogBytes);
  expect((await page.request.delete(`/api/shares/${share.id}`, { headers: { origin } })).status()).toBe(200);
  expect((await page.request.delete(`/api/shares/${share.id}`, { headers: { origin } })).status()).toBe(200);
  for (const suffix of ["/image", "/opengraph-image"]) expect([404, 410]).toContain((await stranger.request.get(path + suffix)).status());
  await viewer.reload();
  await expect(viewer.locator("[data-share-card]")).toHaveCount(0);
  await expect(viewer.locator("main h1")).toBeVisible();
  await viewer.screenshot({ path: `${evidence}/closed-${en ? "en" : "zh"}-${info.project.name}.png`, fullPage: true, animations: "disabled" });
  for (const line of share.snapshot.lines) expect(await viewer.content()).not.toContain(line);
  await stranger.close();
});

test("composer handles rapid selection, failed image and clipboard without losing published share", async ({ page }, info) => {
  const { result } = await seed(page.request);
  await page.addInitScript(() => Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async () => { throw new Error("unavailable"); } } }));
  await page.route("**/s/*/image", route => route.fulfill({ status: 503, body: "unavailable" }));
  await page.goto(`/zh/result/${result.id}`);
  const trigger = page.locator("[data-share-entry] button");
  await trigger.scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${evidence}/entry-${info.project.name}.png`, animations: "disabled" });
  await trigger.click();
  const editor = page.locator('[data-share-state="editing"]');
  await expect(editor).toBeVisible();
  const checks = editor.locator('fieldset input[type="checkbox"]');
  await expect(checks).toHaveCount(6);
  const first = checks.first();
  await first.focus();
  for (let i = 0; i < 10; i++) await first.press("Space");
  await expect(first).toBeFocused();
  expect(await checks.evaluateAll(nodes => nodes.slice(0, 4).filter(node => (node as HTMLInputElement).checked).length)).toBe(3);
  await checks.nth(4).check();
  await checks.nth(5).check();
  await checks.nth(4).uncheck();
  await checks.nth(5).uncheck();
  expect(await editor.locator("[data-share-card]").textContent()).not.toContain("ESTJ");
  await page.screenshot({ path: `${evidence}/editor-${info.project.name}.png`, animations: "disabled" });
  await editor.getByRole("button", { name: "确认公开并生成" }).click();
  const created = page.locator('[data-share-state="created"]');
  await expect(created).toBeVisible();
  await expect(created.getByRole("button", { name: "重新生成图片" })).toBeVisible();
  await expect(created.getByRole("button", { name: "保存图片" })).toBeDisabled();
  await created.getByRole("button", { name: "复制链接", exact: true }).click();
  await expect(created.locator("input[readonly]")).toBeVisible();
  expect(await created.locator("input[readonly]").inputValue()).toMatch(/\/s\/[A-Za-z0-9_-]{32}$/);
  await page.screenshot({ path: `${evidence}/created-fallback-${info.project.name}.png`, animations: "disabled" });
  await page.goto("/zh/my/shares");
  await expect(page.locator("[data-share-card]").first()).toBeVisible();
  await page.screenshot({ path: `${evidence}/management-${info.project.name}.png`, fullPage: true, animations: "disabled" });
});
