import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
import { shareMessages } from "../../src/lib/i18n/messages/share";
import { getQuestionnaire } from "../../src/lib/questionnaires";
const origin = process.env.E2E_BASE_URL ?? "http://localhost:3000";
for (const locale of ["zh", "en"] as const) test(`guide generated image, copy, all-balanced privacy and GA ${locale}`, async ({page,context,browser},info) => {
 const t=shareMessages[locale]; const prefix=locale==="en"?"":"/zh";
 await page.request.get(prefix || "/");
 const q=getQuestionnaire(locale==="en"?"en32-v1":"legacy32-v1")!;
 const r=await page.request.post("/api/results",{data:{questionnaireId:q.id,answers:q.questions.map(x=>({questionId:x.id,value:0}))}});
 const result=(await r.json()).data;
 await page.goto(`${prefix}/result/${result.id}`);
 const entry=page.locator('[data-share-entry]'); await expect(entry).toBeVisible();
 await entry.scrollIntoViewIfNeeded();
 await page.screenshot({path:`docs/verification/share-growth/entry-${locale}-${info.project.name}.png`,animations:"disabled"});
 await entry.getByRole("button",{name:t.create,exact:true}).click();
 const dialog=page.getByRole("dialog");
 await expect(dialog.getByRole("button",{name:t.publish,exact:true})).toBeEnabled();
 await dialog.getByRole("checkbox",{name:t.showType,exact:true}).check();
 await dialog.getByRole("checkbox",{name:t.showDimensions,exact:true}).check();
 await page.screenshot({path:`docs/verification/share-growth/editor-${locale}-${info.project.name}.png`,animations:"disabled"});
 const response=page.waitForResponse(x=>x.url().endsWith('/api/shares')&&x.request().method()==="POST");
 await dialog.getByRole("button",{name:t.publish,exact:true}).click();
 const share=(await(await response).json()).data;
 expect(share.snapshot.typeLabel).toBe(locale==="en"?"Unfolding":"待探索");
 expect(share.snapshot.dimensions.every((x:{state:string})=>x.state==="balanced")).toBe(true);
 expect(JSON.stringify(share.snapshot)).not.toMatch(/ESTJ|INFJ|resultId|answers|values/);
 await expect(dialog.locator('img')).toBeVisible();
 await expect.poll(()=>dialog.locator('img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth===960)).toBe(true);
 await page.screenshot({path:`docs/verification/share-growth/created-${locale}-${info.project.name}.png`,animations:"disabled"});
 await context.grantPermissions(["clipboard-read","clipboard-write"]);
 await dialog.getByRole("button",{name:t.copy,exact:true}).click();
 await expect(dialog.getByRole("button",{name:t.copy,exact:true})).toContainText(t.copied);
 const guest=await browser.newContext({baseURL:origin}); const viewer=await guest.newPage();
 const google:string[]=[];viewer.on('request',r=>{if(/google-analytics|googletagmanager/.test(r.url()))google.push(r.url());});
 await viewer.goto(share.url+`?utm_source=${share.token}&result=${result.id}`);
 await expect(viewer.locator('[data-share-card]')).toBeVisible();
 await expect.poll(()=>viewer.evaluate(()=>window.dataLayer?.length??0)).toBeGreaterThan(0);
 const data=await viewer.evaluate(()=>JSON.stringify(window.dataLayer));
 expect(data).not.toContain(share.token);expect(data).not.toContain(result.id);expect(google).toEqual([]);
 await guest.close();
 await page.goto(`${prefix}/my/shares`);await expect(page.locator("[data-share-manager]")).toBeVisible();
 await page.screenshot({path:`docs/verification/share-growth/management-${locale}-${info.project.name}.png`,fullPage:true,animations:"disabled"});
});
test('creation can finish after closing; owner management recovers it once',async({page})=>{
 await page.request.get('/');const r=(await(await page.request.post('/api/results',{data:{answers:Array(32).fill(0)}})).json()).data;
 await page.goto(`/zh/result/${r.id}`);await page.locator('[data-share-entry]').getByRole('button').click();
 let release!:()=>void;const barrier=new Promise<void>(resolve=>{release=resolve;});
 let saved!:()=>void;const persisted=new Promise<void>(resolve=>{saved=resolve;});
 await page.route('**/api/shares',async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();saved();await barrier;await route.fulfill({response}).catch(()=>{});});
 await page.getByRole('dialog').getByRole('button',{name:shareMessages.zh.publish,exact:true}).click();await persisted;
 await page.getByRole('dialog').getByRole('button',{name:shareMessages.zh.close,exact:true}).click();release();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 const list=(await(await page.request.get('/api/shares')).json()).data;expect(list.items).toHaveLength(1);
 await page.goto('/zh/my/shares');await expect(page.locator('[data-share-manager]')).toBeVisible();
});
test('no signed cookie cannot authorize a write',async({playwright})=>{
 const blank=await playwright.request.newContext({baseURL:origin});
 const response=await blank.post('/api/shares',{headers:{origin},data:{resultId:'ABCDEFGHIJKL',selectedIds:['a','b','c'],showType:false,showDimensions:false,consentVersion:'share-public-v1',requestId:randomUUID()}});
 expect(response.status()).toBe(401);await blank.dispose();
});
